### ISSUE TITLE
A question about Table2 in paper

### ISSUE THREAD

**Issue by Captain2xxx-coder** [echocatzh/GFTNN#1]
In ST-FE scenario, the near-end speech is all zeros, how to make SER  to -5, 5, and 15?

**Comment by echocatzh** [comment]
Thanks for your attention, very good question. 

You can understand it this way, in the final mixed samples, we just removed the near-end speech, because the near-end speech we used in various scenarios is the same, so it can be clear analyze the influence of different echo proportions, mainly for horizontal comparison.

Any questions are welcome
